language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "wget http://d3kbcqa49mib13.cloudfront.net/spark-1.4.0.tgz"
  - "tar -xzf spark-1.4.0.tgz"
  - "mv spark-1.4.0 ~/bin/"
  - "pip install numpy"
# command to run tests
script: ./run.sh